name: Publish package

on:
  push:
    tags: ['*/v*']

jobs:
  publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy README
        run: cp README.md packages/plugin

      - name: Test
        run: npm run test

      - name: Parse package name from tag
        id: parse-tag
        run: |
          TAG_NAME="${{ github.ref_name }}"
          PACKAGE_NAME=$(echo "$TAG_NAME" | awk -F '/' '{print $1}')
          echo "package-name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Find package path
        id: find-path
        run: |
          PACKAGE_PATH=$(jq -r '.packages | to_entries[] | select(.value."package-name" == "${{ env.PACKAGE_NAME }}") | .key' release-please-config.json)
          echo "package-path=${PACKAGE_PATH}" >> $GITHUB_OUTPUT
        env:
          PACKAGE_NAME: '${{ steps.parse-tag.outputs.package-name }}'

      - name: Publish
        run: npm publish
        working-directory: ${{ steps.find-path.outputs.package-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
