name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Check for release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: googleapis/release-please-action@v4.1.1
